### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by Jam2400** [mctoolbox/Beebliotheca#2]
Stuff like this happens: 
http://prntscr.com/5qgbyt

When a user hasn't bought the item, it doesn't appear 'null' in the API. The variable just isn't there, not sure for a way around it.

**Comment by DevRoMc** [comment]
Thanks for reporting this bug. This will be fixed in the next push!

**Comment by DevRoMc** [comment]
Fixed in latest commit.
